fix: Revert github workflows related file since it blocks git push
Error: refusing to allow an OAuth App to create or update workflow
`.github/workflows/node.js.yml` without `workflow` scope